"""add user_items table

Revision ID: d4b7bb76c25c
Revises: a1f3c9d2e4b5
Create Date: 2026-08-02 22:35:25.520192

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b7bb76c25c'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9d2e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Matches the mock catalog mobile/app/(tabs)/shop.tsx showed in Week 1 —
# fixed IDs so this migration is idempotent-ish and the seed is traceable.
SHOP_ITEMS = [
    {"id": "a1000000-0000-4000-8000-000000000001", "name": "Lure Scent", "type": "consumable", "cost": 50, "effect": "+10% capture rate for 30 min"},
    {"id": "a1000000-0000-4000-8000-000000000002", "name": "Rarity Scanner", "type": "consumable", "cost": 120, "effect": "Reveals rarity tier before capture"},
    {"id": "a1000000-0000-4000-8000-000000000003", "name": "Battle Shield", "type": "consumable", "cost": 80, "effect": "Blocks one loss streak penalty"},
    {"id": "a1000000-0000-4000-8000-000000000004", "name": "Golden Frame", "type": "cosmetic", "cost": 200, "effect": "Profile-only cosmetic, no gameplay effect"},
]

shop_items_table = sa.table(
    "shop_items",
    sa.column("id", sa.Uuid()),
    sa.column("name", sa.String()),
    sa.column("type", sa.String()),
    sa.column("cost", sa.Integer()),
    sa.column("effect", sa.String()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        shop_items_table,
        [{**item, "id": uuid.UUID(item["id"])} for item in SHOP_ITEMS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        shop_items_table.delete().where(
            shop_items_table.c.id.in_([uuid.UUID(item["id"]) for item in SHOP_ITEMS])
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_items')
    # ### end Alembic commands ###
